trigger: none
#- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    java/mvn verify package sonar:sonar -Dsonar.host.url=$(SONARCLOUDURL) -Dsonar.organization=$(SONARCLOUDORGANIZATION) -Dsonar.projectKey=$(SONARCLOUDPROJECTKEY) -Dsonar.login=$(sonarcloudtoken)
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Sonar cloud connecting'